baseURL = 'https://caldwell-matthew.github.io/lightintheironcage/'
CanonifyUrls = true 
languageCode = 'en-us'
title = 'Light in the Iron Cage'
theme = 'PaperMod'

[params]
env = "production"
mainSections = ["/_index/"]
ShowShareButtons = true
ShowReadingTime = true
ShowBreadCrumbs = true
ShowToc = true
TocOpen = false
ShowPostNavLinks = true

[params.homeInfoParams]
Title = "All my links"
Content = "Best way to reach me is by email or discord, but I am also on the following sites."

[[params.socialIcons]]
name = "email"
url = "mailto:caldwell.j.matthew@gmail.com?subject=Light%20in%20the%20Iron%20Cage&body=A%20Question%2C%20Comment%2C%20or%20Concern%3F"

[[params.socialIcons]]
name = "discord"
url = "https://discord.com/users/mattancholic"

[[params.socialIcons]]
name = "github"
url = "https://github.com/caldwell-matthew"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/caldwell-matthew/"

# [[params.socialIcons]]
# name = "about"
# url = "about/"

[params.editPost]
URL = "https://github.com/caldwell-matthew/lightintheironcage/tree/master/content"
Text = "Suggest Changes"
appendFilePath = true

[[menu.main]]
identifier = "Search"
name = "Search"
url = "search/"
weight = 10

[[menu.main]]
identifier = "Posts"
name = "Posts"
url = "posts/"
weight = 20

[[menu.main]]
identifier = "Tags"
name = "Tags"
url = "tags/"
weight = 30

[[menu.main]]
identifier = "Help"
name = "Help"
url = "help/"
weight = 40

[[menu.main]]
identifier = "About Me"
name = "About Me"
url = "about/"
weight = 50

[outputs]
home = [ "HTML", "RSS", "JSON" ]