baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Light in the Iron Cage'
theme = 'PaperMod'

[params]
env = "production"
mainSections = ["/_index/"]

[[menu.main]]
identifier = "Search"
name = "Search"
url = "/search/"
weight = 10

[[menu.main]]
identifier = "Posts"
name = "Posts"
url = "/posts/"
weight = 20

[[menu.main]]
identifier = "Tags"
name = "Tags"
url = "/tags/"
weight = 30

[[menu.main]]
identifier = "Help"
name = "Help"
url = "/help/"
weight = 40

[params.homeInfoParams]
Title = "Hi there wave"
Content = "Can be Info, links, about..."
    
[[socialIcons]]
name = "<platform 2>"
url = "<link>"

[outputs]
home = [ "HTML", "RSS", "JSON" ]